### ISSUE TITLE
All PAL filesystem tests fail 

### ISSUE THREAD

**Issue by avolinski** [ARMmbed/sd-driver#39] opened 2017-07-09 16:20 UTC
Hi,

PAL File System tests fail on all mbedOS running devices after changes introduced several days ago into sd-driver repository.
https://jenkins-internal.mbed.com/view/PAL/job/PAL-Tests-Pipeline-Nightly/306/testReport/

was there some basic change in the init behavior?
cc @geky @simonqhughes

**Comment by deepikabhavnani** [comment] 2017-07-10 19:26
Yes.. init behavior was changed and instead polling, timeouts for command was implemented.
@avolinski - May i know which SD card is used for PAL ?

If possible can you send me SD Command trace for any failing test by enabling
'SD_DBG'  and 'SD_CMD_TRACE' flag in SDBlockDevice.cpp.

**Comment by netanelgonen** [comment] 2017-07-11 10:27
[sd-logError.txt](https://github.com/ARMmbed/sd-driver/files/1138546/sd-logError.txt)
@deepikabhavnani please see attched file
im using transcend 8 gb micro sd hc class 10

**Comment by netanelgonen** [comment] 2017-07-11 10:38
@galc @JanneKiiskila

**Comment by JanneKiiskila** [comment] 2017-07-11 11:33
Are you calling the `sd.init()` in the pal tests?

**Comment by netanelgonen** [comment] 2017-07-11 12:19
@JanneKiiskila actually no...
following this https://github.com/ARMmbed/sd-driver/blob/master/TESTS/filesystem/basic/basic.cpp example i have not seen any use of it...

i have added the function but the errors persist, send a new log?(the errors are the same...)

**Comment by JanneKiiskila** [comment] 2017-07-11 12:27
Well, if you did do it - and caught an error there, you could immediately stop all file tests.

**Comment by netanelgonen** [comment] 2017-07-11 12:42
sd.init returns 0

**Comment by netanelgonen** [comment] 2017-07-12 07:46
@deepikabhavnani is there any update with this? 

this actually blocks all our file system tests

**Comment by JanneKiiskila** [comment] 2017-07-12 08:00
@netanelgonen  - you could try the PR; https://github.com/ARMmbed/sd-driver/pull/41

**Comment by deepikabhavnani** [comment] 2017-07-12 15:41
@netanelgonen - Did you get the chance to test PAL test with #41 fix? 

After above fix, I have seen SPI block read failures with few SD cards, and fixing that might take sometime in mbed-os. https://github.com/ARMmbed/mbed-os/pull/4744

Quick temporary solution to that would be to use SPI byte read.

**Comment by netanelgonen** [comment] 2017-07-13 08:00
@deepikabhavnani #41 did not solve the problem

**Comment by deepikabhavnani** [comment] 2017-07-13 08:35
Does it still fail in initialisation?

**Comment by JanneKiiskila** [comment] 2017-07-13 08:36
Is this the root cause for the issue now? https://github.com/ARMmbed/mbed-os/issues/4743 
Or is it something else?

**Comment by JanneKiiskila** [comment] 2017-07-17 09:33
Can we get some updates on this? @netanelgonen  - can you post latest traces?

**Comment by netanelgonen** [comment] 2017-07-17 09:39
@JanneKiiskila unfortunately the PR is not solving the issue and the traces are them same..
if there is a need for the new trace i will upload them later today.

**Comment by deepikabhavnani** [comment] 2017-07-17 11:57
Will it be possible to share SPI bus trace?

**Comment by netanelgonen** [comment] 2017-07-18 08:05
please view the attched file
[sdlog.txt](https://github.com/ARMmbed/sd-driver/files/1155083/sdlog.txt)

**Comment by deepikabhavnani** [comment] 2017-07-18 10:52
Initialisation is successful from log, do you get the return (0 -success) from init? Not sure why re-init is done?

Card CSD in this log was success and got 8GB card size

**Comment by netanelgonen** [comment] 2017-07-18 11:03
the init is successful but we cannot read/write from the sd card...

**Comment by netanelgonen** [comment] 2017-07-18 11:07
we encountering inconsistent behavior with the new sd-driver,
sometime all test fails, sometimes all pass, and sometimes half pass and half fail... 
it may be timing issues... 
this is a link to our jenkins job: 
https://jenkins-internal.mbed.com/view/PAL/job/PAL-Tests-Pipeline-Nightly/317/testReport/

the file system tests start failing after your update.
in meanwhile do you have a tag before the update that we can use?

**Comment by deepikabhavnani** [comment] 2017-07-18 14:37
PAL failures are with K64F devices, which is related to https://github.com/ARMmbed/mbed-os/issues/4743, SPI block reads fail or K64F. 

For older versions and tag please refer to readme, or use  'git tag -n' command in driver folder

**Comment by avolinski** [comment] 2017-08-02 17:03
one small note, originally pal failures were not only with k64f devices, but with odin boards too.
so failures are not bound to one platform
https://jenkins-internal.mbed.com/view/PAL/job/PAL-Tests-Pipeline-Nightly/306/testReport/

**Comment by deepikabhavnani** [comment] 2017-08-04 15:43
@avolinski @netanelgonen @JanneKiiskila - I am closing this issue. If PAL failures related to SD device are found, please open new issue.

**Closed by deepikabhavnani** 2017-08-04 15:43 UTC
